version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydatabase

  db:
    image: postgres:alpine
    volumes:
      - ./backend/database_init.sql:/docker-entrypoint-initdb.d/database_init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
